### ISSUE TITLE
check-script-has-no-table-name fails with Jinja-generated CTEs

### ISSUE THREAD

**Issue by MartinGuindon** [dbt-checkpoint/dbt-checkpoint#15]
**Describe the bug**
check-script-has-no-table-name fails with Jinja-generated CTEs

**To Reproduce**
Generate a series of CTEs through a Jinja loop such as:
```
{% set positions = ['left', 'right', 'center'] %}

with
{% for p in positions %}
    
    cte_{{ p }} as (
        select '{{ p }}' as position
    ),

{% endfor %}

unioned as (
    select * from cte_left
    union all
    select * from cte_right
    union all
    select * from cte_center
)

select * from unioned
```

The hook will complain that cte_left, cte_right and cte_center does not use source() or ref() macros for tables.

**Expected behavior**
I assume that this hook should inspect the compiled version rather than the raw version?

**Version:**
v0.1.1 bleeding edge

**Comment by tomsej** [comment]
This one is a little bit more complicated. Think I can create a flag to decide if check should be run on compiled or not-compiled sql. Will think about this!

**Comment by tomsej** [comment]
I have added a little bit of a hacky way on how to prevent this. Use `--ignore-dotless-table` (consider all tables without dot in name as CTE).
