### ISSUE TITLE
Add support for Slim CI

### ISSUE THREAD

**Issue by MartinGuindon** [dbt-checkpoint/dbt-checkpoint#22]
**Describe the feature you'd like**
Currently, the dbt-run hook will pass all staged models, possibly causing a re-run of the project that is not necessary, which can be problematic on large projects with a very long runtime.

It would be ideal to be able to support dbt's built-in [Slim CI support](https://docs.getdbt.com/docs/guides/best-practices#run-only-modified-models-to-test-changes-slim-ci). This way, if the developer has already ran and tested the project and made no further changes, the hook will detect this and skip the run. If, however, the developer did not run the project, the hook would run the changed models automatically, ensuring that nothing is being committed without successfully running.

**Comment by tomsej** [comment]
Hey @MartinGuindon I just fixed that in `bleeding edge` version. You can run it with:

```
 hooks:
 - id: dbt-compile
   args: ["--models", "state:modified", "--cmd-flags", "++defer", "++state", "path/to/artifacts", "--"]
```
beware you need to change `--defer` and `--state` to `++defer` and `++state` since there are 2 argument parsers.

Let me know if it works for you
