### ISSUE TITLE
Cannot use the action in a workflow

### ISSUE THREAD

**Issue by Sh1n** [dbt-checkpoint/dbt-checkpoint#26]
**Describe the bug**
Hi there, first of all thanks for the efforts in developing this library. We are trying to include this step in our workflow, but we are facing an issue related to the docker image. It cannot pull it:

![Screenshot 2021-04-23 at 10 31 04](https://user-images.githubusercontent.com/767394/115844375-0da8b100-a420-11eb-859a-daec09f7975a.png)
 
Might the issue be related to the actual image defined in action.yaml ?

**To Reproduce**
1. follow either the readme example or the snippet as reported in the marketplace

Example configuration:
```{yaml}
     - id: dbt_checks
        uses: offbi/pre-commit-dbt@v1.0.0
        env:
          [ ... ]
        with:
          args: run --files ${{ steps.file_changes.outputs.files }}
```

**Version:**
v1.0.0

**Comment by tomsej** [comment]
Thank you for posting this. Will look on that

**Comment by natarajanc-prodigygame** [comment]
i also faced the same issue - also how do i use the hook syntax here?
can i do the following to run `dbt-compile` hook in my github action?
```sh
with:
         args: dbt-compile --model-prefix + --cmd-flags ++project-dir dbt_pipelines --
```

**Comment by tlfbrito** [comment]
I'm having the same issue

**Comment by emily-hawkins** [comment]
Hi! I am also having this issue

**Comment by tomsej** [comment]
Thank you all! This will be fixed in the new version.
