### ISSUE TITLE
Add inexistant columns in documentation test

### ISSUE THREAD

**Issue by qmoret** [dbt-checkpoint/dbt-checkpoint#35]
**Describe the feature you'd like**
If a column in the properties file is not in the related model, this will not be catched by dbt, and may cause the documentation to be out of sync with the model exposed in the database. It would be super helpful for me to have this as a pre-commit check that ensures that all columns in the documentation are in the model.

**Additional context**
In the `catalog.json`, dbt stores all the existing columns in a model, which could help to identify which columns in the properties file are not in the model.

**Comment by tomsej** [comment]
Hi @qmoret, correct me if I am wrong but I think that this hook should check that - https://github.com/offbi/pre-commit-dbt/blob/main/pre_commit_dbt/check_model_has_all_columns.py.

**Comment by qmoret** [comment]
Oh indeed apologies, I hadn't seen that it was also checking for deleted columns, that's great ! 
In my case we have only a fraction of our columns that are documented, so the full hook would be an overkill. But we would still like to check that those that are documented are not deleted. Maybe the hook could be split in two ?
