### ISSUE TITLE
check-script-has-no-table-name doesn't ignore text within Jinja comment blocks

### ISSUE THREAD

**Issue by neddonaldson** [dbt-checkpoint/dbt-checkpoint#9]
**Describe the bug**
If we use the word "from" or "join" in a Jinja comment block the parser thinks that the next word is the name of a table or CTE and passes an error. 

sql: 
```
{# This is a test of the check-script-has-no-table-name hook, from pre-commit-dbt

We would expect the hook to ignore this text because it is in a jinja comment block
and not actually a join to any other table.

#}
``` 

output from `pre-commit run` 
```
Check the script has not table name......................................Failed
- hook id: check-script-has-no-table-name
- exit code: 1

test.sql: does not use source() or ref() macros for tables:
- pre-commit-dbt
- to
```

**To Reproduce**
1. create a new sql file 
2. add into the file
```
{# This is a test of the check-script-has-no-table-name hook, from pre-commit-dbt

We would expect the hook to ignore this text because it is in a jinja comment block
and not actually a join to any other table.

#}
```
3. Run pre-commit with the check-script-has-no-table-name hook enabled 

**Expected behavior**
I'd expect the parser to ignore comment blocks since it's not important if they don't use `ref() or source()` 

**Version:**
v0.1.1

**Comment by tomsej** [comment]
Good catch @neddonaldson!! Thanks a lot. I fixed that in #11. If you do not wait for a new version of `pre-commit-dbt` you can run `pre-commit autoupdate --bleeding-edge` to update to `HEAD`.
